// Generated by Selenium IDE
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Threading;
using OpenQA.Selenium;
using OpenQA.Selenium.Chrome;
using OpenQA.Selenium.Firefox;
using OpenQA.Selenium.Remote;
using OpenQA.Selenium.Support.UI;
using OpenQA.Selenium.Interactions;
using NUnit.Framework;
[TestFixture]
public class CheckoutTest {
  private IWebDriver driver;
  public IDictionary<string, object> vars {get; private set;}
  private IJavaScriptExecutor js;
  [SetUp]
  public void SetUp() {
    driver = new ChromeDriver();
    js = (IJavaScriptExecutor)driver;
    vars = new Dictionary<string, object>();
  }
  [TearDown]
  protected void TearDown() {
    driver.Quit();
  }
  [Test]
  public void checkout() {
    driver.Navigate().GoToUrl("https://demowebshop.tricentis.com/");
    driver.Manage().Window.Size = new System.Drawing.Size(1163, 816);
    driver.FindElement(By.CssSelector(".ico-cart > .cart-label")).Click();
    driver.FindElement(By.Id("checkout")).Click();
    driver.FindElement(By.CssSelector(".ui-button-icon-primary")).Click();
    driver.FindElement(By.Id("termsofservice")).Click();
    driver.FindElement(By.Id("checkout")).Click();
  }
}
